name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Remove 'patches' directories from all results
        run: find . -type d -name 'patches' -exec rm -rf {} +

      - name: Setup Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: 23.1.0

      - name: Install Dependencies
        run: cd webpage && npm install
        
      - name: Deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/repairbench/repairbench.github.io.git
          cd webpage && npm run deploy -- -u "André Silva <andre15andre@hotmail.com>"
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
          CI: ""
