name: Mirror Repository

on:
  push:
    branches:
      - gh-pages

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Push to mirror repository
        uses: pixta-dev/repository-mirroring-action@674e65a7d483ca28dafaacba0d07351bdcc8bd75
        with:
          target_repo_url: 
            git@github.com:repairbench/repairbench.github.io.git
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}